# Generated by Django 3.1.6 on 2021-02-08 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('main_description', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('temperature', models.FloatField(null=True)),
                ('max_temp', models.FloatField(null=True)),
                ('min_temp', models.FloatField(null=True)),
                ('lat', models.FloatField(null=True)),
                ('lng', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalWeather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('time', models.CharField(max_length=500, null=True)),
                ('temp_day', models.CharField(max_length=500, null=True)),
                ('temp_night', models.CharField(max_length=500, null=True)),
                ('sunrise', models.CharField(max_length=500, null=True)),
                ('sunset', models.CharField(max_length=500, null=True)),
                ('weather', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.weather')),
            ],
        ),
    ]
