# Generated by Django 3.1.6 on 2021-02-09 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210208_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalweather',
            name='weather',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.weather'),
        ),
    ]
