# Generated by Django 3.1.6 on 2021-02-09 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210209_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weather',
            options={'ordering': ['-created']},
        ),
    ]
